export let tiles = [
    {
        "id": 1,
        "title": "Achari Khakhra",
        "short_description": "Achari khakhra is a spicy khakhra. You will fall in love with its taste.",
        "long_description": "There are variations in the method of preparation, but generally the following method is observed. Wheat flour (and/or refined flour), salt and masala are mixed. Oil, water or milk are added and kneaded to make a soft dough. This dough is then rolled into small balls and flattened. These are then roasted over slow heat and pressed via wooden press, until crisp and light brown in color. This popular Jain and Gujarati farsan has been on my mind for a while. Just a week before the noodle khakhra discovery, I’d received a dabba full of khakhras from my sister-in-law from the Gujarati side of my family. She’d asked a khakhra maharaj, whose skill has been preferred by our kin for years, to make stacks of the crisp roasted snacks in her kitchen, so that she could stock up as well as distribute them among us. We’d asked for sada, mari (pepper), nachni and khichdi (a slightly sweet khakhra made from khichdi), and had them with hummus, peanut butter, coconut oil and podi, ghee and methi seed-based sambhaar (not to be confused with the sambhar had with dosa), and dahi chutney (not all at the same time). The good thing about getting a khakhra maharaj is that you have control over the quality of ingredients. Another friend of mine had spoken to me about a travelling saleslady, a khakhrawali as she called herself, supplying homemade khakhras to homes in Cuffe Parade. As it turns out, there are many such khakhrawalis in the city – friends in Malabar Hill, Khar and Kandivali said they have their favourites. To prepare the Khakhra, take a bowl add whole wheat flour, little salt as per taste, chilli powder, ajwain (bishop’s weed or carom seed), kasuri methi (dried methi leaves), turmeric, oil and mix well to form a medium stiff dough. Rest it aside for 20 mins. Now divide the dough into equal parts of small roundels and make a phulka or chapatti size that has to be thin as a paper. Take a tava cook the paper thin roti on both side, keep pressing the roti with a cloth to make it crispy and flaky papad like till they turn slightly golden brown color. The Khakhra is more like a readymade roasted papad. They are also tailor- made range according to the taste of the customers and also for diabetic patients preparing the karela khakhra or methi khakhra and many more. It’s a very crispy, crunchy, mouth watering tasty nutritious and a light snack.",
        "image": "images/Achari_Khakhra.jpg"
    },
    {
        "id": 2,
        "title": "Methi Khakhra",
        "short_description": "Methi khakhra is a mast khakhra. You will fall in love with its taste.",
        "long_description": "There are variations in the method of preparation, but generally the following method is observed. Wheat flour (and/or refined flour), salt and masala are mixed. Oil, water or milk are added and kneaded to make a soft dough. This dough is then rolled into small balls and flattened. These are then roasted over slow heat and pressed via wooden press, until crisp and light brown in color. This popular Jain and Gujarati farsan has been on my mind for a while. Just a week before the noodle khakhra discovery, I’d received a dabba full of khakhras from my sister-in-law from the Gujarati side of my family. She’d asked a khakhra maharaj, whose skill has been preferred by our kin for years, to make stacks of the crisp roasted snacks in her kitchen, so that she could stock up as well as distribute them among us. We’d asked for sada, mari (pepper), nachni and khichdi (a slightly sweet khakhra made from khichdi), and had them with hummus, peanut butter, coconut oil and podi, ghee and methi seed-based sambhaar (not to be confused with the sambhar had with dosa), and dahi chutney (not all at the same time). The good thing about getting a khakhra maharaj is that you have control over the quality of ingredients. Another friend of mine had spoken to me about a travelling saleslady, a khakhrawali as she called herself, supplying homemade khakhras to homes in Cuffe Parade. As it turns out, there are many such khakhrawalis in the city – friends in Malabar Hill, Khar and Kandivali said they have their favourites. To prepare the Khakhra, take a bowl add whole wheat flour, little salt as per taste, chilli powder, ajwain (bishop’s weed or carom seed), kasuri methi (dried methi leaves), turmeric, oil and mix well to form a medium stiff dough. Rest it aside for 20 mins. Now divide the dough into equal parts of small roundels and make a phulka or chapatti size that has to be thin as a paper. Take a tava cook the paper thin roti on both side, keep pressing the roti with a cloth to make it crispy and flaky papad like till they turn slightly golden brown color. The Khakhra is more like a readymade roasted papad. They are also tailor- made range according to the taste of the customers and also for diabetic patients preparing the karela khakhra or methi khakhra and many more. It’s a very crispy, crunchy, mouth watering tasty nutritious and a light snack.",
        "image": "images/Methi_Khakhra.jpg"
    },
    {
        "id": 3,
        "title": "Pizza Khakhra",
        "short_description": "Pizza khakhra is the best khakhra. You will fall in love with its taste.",
        "long_description": "There are variations in the method of preparation, but generally the following method is observed. Wheat flour (and/or refined flour), salt and masala are mixed. Oil, water or milk are added and kneaded to make a soft dough. This dough is then rolled into small balls and flattened. These are then roasted over slow heat and pressed via wooden press, until crisp and light brown in color. This popular Jain and Gujarati farsan has been on my mind for a while. Just a week before the noodle khakhra discovery, I’d received a dabba full of khakhras from my sister-in-law from the Gujarati side of my family. She’d asked a khakhra maharaj, whose skill has been preferred by our kin for years, to make stacks of the crisp roasted snacks in her kitchen, so that she could stock up as well as distribute them among us. We’d asked for sada, mari (pepper), nachni and khichdi (a slightly sweet khakhra made from khichdi), and had them with hummus, peanut butter, coconut oil and podi, ghee and methi seed-based sambhaar (not to be confused with the sambhar had with dosa), and dahi chutney (not all at the same time). The good thing about getting a khakhra maharaj is that you have control over the quality of ingredients. Another friend of mine had spoken to me about a travelling saleslady, a khakhrawali as she called herself, supplying homemade khakhras to homes in Cuffe Parade. As it turns out, there are many such khakhrawalis in the city – friends in Malabar Hill, Khar and Kandivali said they have their favourites. To prepare the Khakhra, take a bowl add whole wheat flour, little salt as per taste, chilli powder, ajwain (bishop’s weed or carom seed), kasuri methi (dried methi leaves), turmeric, oil and mix well to form a medium stiff dough. Rest it aside for 20 mins. Now divide the dough into equal parts of small roundels and make a phulka or chapatti size that has to be thin as a paper. Take a tava cook the paper thin roti on both side, keep pressing the roti with a cloth to make it crispy and flaky papad like till they turn slightly golden brown color. The Khakhra is more like a readymade roasted papad. They are also tailor- made range according to the taste of the customers and also for diabetic patients preparing the karela khakhra or methi khakhra and many more. It’s a very crispy, crunchy, mouth watering tasty nutritious and a light snack.",
        "image": "images/Pizza_Khakhra.jpg"
    },
    {
        "id": 4,
        "title": "Panipuri Khakhra",
        "short_description": "Panipuri khakhra is an awesome khakhra. You will fall in love with its taste.",
        "long_description": "There are variations in the method of preparation, but generally the following method is observed. Wheat flour (and/or refined flour), salt and masala are mixed. Oil, water or milk are added and kneaded to make a soft dough. This dough is then rolled into small balls and flattened. These are then roasted over slow heat and pressed via wooden press, until crisp and light brown in color. This popular Jain and Gujarati farsan has been on my mind for a while. Just a week before the noodle khakhra discovery, I’d received a dabba full of khakhras from my sister-in-law from the Gujarati side of my family. She’d asked a khakhra maharaj, whose skill has been preferred by our kin for years, to make stacks of the crisp roasted snacks in her kitchen, so that she could stock up as well as distribute them among us. We’d asked for sada, mari (pepper), nachni and khichdi (a slightly sweet khakhra made from khichdi), and had them with hummus, peanut butter, coconut oil and podi, ghee and methi seed-based sambhaar (not to be confused with the sambhar had with dosa), and dahi chutney (not all at the same time). The good thing about getting a khakhra maharaj is that you have control over the quality of ingredients. Another friend of mine had spoken to me about a travelling saleslady, a khakhrawali as she called herself, supplying homemade khakhras to homes in Cuffe Parade. As it turns out, there are many such khakhrawalis in the city – friends in Malabar Hill, Khar and Kandivali said they have their favourites. To prepare the Khakhra, take a bowl add whole wheat flour, little salt as per taste, chilli powder, ajwain (bishop’s weed or carom seed), kasuri methi (dried methi leaves), turmeric, oil and mix well to form a medium stiff dough. Rest it aside for 20 mins. Now divide the dough into equal parts of small roundels and make a phulka or chapatti size that has to be thin as a paper. Take a tava cook the paper thin roti on both side, keep pressing the roti with a cloth to make it crispy and flaky papad like till they turn slightly golden brown color. The Khakhra is more like a readymade roasted papad. They are also tailor- made range according to the taste of the customers and also for diabetic patients preparing the karela khakhra or methi khakhra and many more. It’s a very crispy, crunchy, mouth watering tasty nutritious and a light snack.",
        "image": "images/Panipuri_Khakhra.jpg"
    },
    {
        "id": 5,
        "title": "Cheese Khakhra",
        "short_description": "Cheese khakhra is a great khakhra. You will fall in love with its taste.",
        "long_description": "There are variations in the method of preparation, but generally the following method is observed. Wheat flour (and/or refined flour), salt and masala are mixed. Oil, water or milk are added and kneaded to make a soft dough. This dough is then rolled into small balls and flattened. These are then roasted over slow heat and pressed via wooden press, until crisp and light brown in color. This popular Jain and Gujarati farsan has been on my mind for a while. Just a week before the noodle khakhra discovery, I’d received a dabba full of khakhras from my sister-in-law from the Gujarati side of my family. She’d asked a khakhra maharaj, whose skill has been preferred by our kin for years, to make stacks of the crisp roasted snacks in her kitchen, so that she could stock up as well as distribute them among us. We’d asked for sada, mari (pepper), nachni and khichdi (a slightly sweet khakhra made from khichdi), and had them with hummus, peanut butter, coconut oil and podi, ghee and methi seed-based sambhaar (not to be confused with the sambhar had with dosa), and dahi chutney (not all at the same time). The good thing about getting a khakhra maharaj is that you have control over the quality of ingredients. Another friend of mine had spoken to me about a travelling saleslady, a khakhrawali as she called herself, supplying homemade khakhras to homes in Cuffe Parade. As it turns out, there are many such khakhrawalis in the city – friends in Malabar Hill, Khar and Kandivali said they have their favourites. To prepare the Khakhra, take a bowl add whole wheat flour, little salt as per taste, chilli powder, ajwain (bishop’s weed or carom seed), kasuri methi (dried methi leaves), turmeric, oil and mix well to form a medium stiff dough. Rest it aside for 20 mins. Now divide the dough into equal parts of small roundels and make a phulka or chapatti size that has to be thin as a paper. Take a tava cook the paper thin roti on both side, keep pressing the roti with a cloth to make it crispy and flaky papad like till they turn slightly golden brown color. The Khakhra is more like a readymade roasted papad. They are also tailor- made range according to the taste of the customers and also for diabetic patients preparing the karela khakhra or methi khakhra and many more. It’s a very crispy, crunchy, mouth watering tasty nutritious and a light snack.",
        "image": "images/Cheese_Khakhra.jpg"
    },
    {
        "id": 6,
        "title": "Plain Khakhra",
        "short_description": "Plain khakhra is the mindblowing khakhra. You will fall in love with its taste.",
        "long_description": "There are variations in the method of preparation, but generally the following method is observed. Wheat flour (and/or refined flour), salt and masala are mixed. Oil, water or milk are added and kneaded to make a soft dough. This dough is then rolled into small balls and flattened. These are then roasted over slow heat and pressed via wooden press, until crisp and light brown in color. This popular Jain and Gujarati farsan has been on my mind for a while. Just a week before the noodle khakhra discovery, I’d received a dabba full of khakhras from my sister-in-law from the Gujarati side of my family. She’d asked a khakhra maharaj, whose skill has been preferred by our kin for years, to make stacks of the crisp roasted snacks in her kitchen, so that she could stock up as well as distribute them among us. We’d asked for sada, mari (pepper), nachni and khichdi (a slightly sweet khakhra made from khichdi), and had them with hummus, peanut butter, coconut oil and podi, ghee and methi seed-based sambhaar (not to be confused with the sambhar had with dosa), and dahi chutney (not all at the same time). The good thing about getting a khakhra maharaj is that you have control over the quality of ingredients. Another friend of mine had spoken to me about a travelling saleslady, a khakhrawali as she called herself, supplying homemade khakhras to homes in Cuffe Parade. As it turns out, there are many such khakhrawalis in the city – friends in Malabar Hill, Khar and Kandivali said they have their favourites. To prepare the Khakhra, take a bowl add whole wheat flour, little salt as per taste, chilli powder, ajwain (bishop’s weed or carom seed), kasuri methi (dried methi leaves), turmeric, oil and mix well to form a medium stiff dough. Rest it aside for 20 mins. Now divide the dough into equal parts of small roundels and make a phulka or chapatti size that has to be thin as a paper. Take a tava cook the paper thin roti on both side, keep pressing the roti with a cloth to make it crispy and flaky papad like till they turn slightly golden brown color. The Khakhra is more like a readymade roasted papad. They are also tailor- made range according to the taste of the customers and also for diabetic patients preparing the karela khakhra or methi khakhra and many more. It’s a very crispy, crunchy, mouth watering tasty nutritious and a light snack.",
        "image": "images/Plain_Khakhra.jpg"
    }
]